spring:
  application:
    name: banking-service
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:membership
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create


logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL=DEBUG:
    org.hibernate.type.descriptor.sql.BasicBinder=TRACE:

springdoc:
   swagger-ui:
        path: /swagger-ui.html
server:
    port: 10020